export const SET_ROUTER_ABI = "SET_ROUTER_ABI";

export const SET_BUSTPAIR_ABI = "SET_BUSTPAIR_ABI";

export const SET_WBNB_ABI = "SET_WBNB_ABI";

export const SET_BUSTFACTORY_ABI = "SET_BUSTFACTORY_ABI";

export const CONNECT_ETH_WALLET = "CONNECT_ETH_WALLET";

export const DISCONNECT_ETH_WALLET = "DISCONNECT_ETH_WALLET";