export const SET_ROUTER_ABI = "SET_ROUTER_ABI";

export const SET_BUSTPAIR_ABI = "SET_BUSTPAIR_ABI";

export const SET_WBNB_ABI = "SET_WBNB_ABI";

export const SET_BUSTFACTORY_ABI = "SET_BUSTFACTORY_ABI";

export const CONNECT_ETH_WALLET = "CONNECT_ETH_WALLET";

export const DISCONNECT_ETH_WALLET = "DISCONNECT_ETH_WALLET";

export const INCREMENT_SLIPPAGE = "INCREMENT_SLIPPAGE"

export const DECREMENT_SLIPPAGE = "DECREMENT_SLIPPAGE"

export const INCREMENT_DEADLINE = "INCREMENT_DEADLINE"

export const DECREMENT_DEADLINE = "DECREMENT_DEADLINE"

export const INITIALRUST = "INITIALRUST"

export const INITIALBUST = "INITIALBUST"